ci:
  autofix_prs: true
  autoupdate_schedule: monthly

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-symlinks
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-ast
  - id: requirements-txt-fixer
  - id: check-builtin-literals
  - id: debug-statements
  - id: fix-encoding-pragma


- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort
    entry: isort
    require_serial: true
    language: python
    types:
    - python

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.3.0
  hooks:
  - id: nbqa-black
    additional_dependencies:
    - black==22.1.0
  - id: nbqa-isort
    additional_dependencies:
    - isort==5.10.1

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
